-- SQL 고득점 Kit
-- 분류 : JOIN
SELECT AI.ANIMAL_ID
     , AI.ANIMAL_TYPE
     , AI.NAME
  FROM ANIMAL_INS AI
     , ANIMAL_OUTS AO
 WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
   AND AI.SEX_UPON_INTAKE LIKE 'In%'
   AND AO.SEX_UPON_OUTCOME NOT LIKE 'In%'
 ORDER BY ANIMAL_ID;