-- SQL 고득점 Kit
-- 분류 : GROUP BY
SELECT B.HOUR
     , COUNT(A.HOUR) CNT
FROM 
  (SELECT TO_CHAR(DATETIME,'HH24') HOUR 
    FROM ANIMAL_OUTS
  ) A, 
  (SELECT LEVEL-1 HOUR 
     FROM DUAL CONNECT BY LEVEL <= 24
  ) B
WHERE B.HOUR = A.HOUR(+)
GROUP BY b.HOUR
ORDER BY b.HOUR;